### ISSUE TITLE
multiselect

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/BIMsurfer-before2019#135]
selecting multiple objects

**Comment by xeolabs** [comment]
Do you mean selection with the mouse, ie. with SHIFT held down to multiselect?

Multiselect is currently supported programmatically via the API - for example:

``` javascript
bimSurfer.setSelectionState({ids: ["object3", "object2", "object4", "object6"], selected: true });
var selected = bimSurfer.getSelected();
bimSurfer.viewFit({ ids: selected, animate: true });

```

**Comment by aothms** [comment]
Indeed, I would say [shift] to toggle selection of (additional) objects. Also, there needs to be a visual indication of selected elements. Which I would propose to be the white bounding box or sth similar.

Can you make this white bounding box always visible regardless of whats in de depth buffer, e.g I guess do a `gl.clear(gl.DEPTH_BUFFER_BIT)` before drawing it? Or something else. I also quite like the selection indication of Blender, i.e. a stencilled (>= 2px thick) wireframe render of the object to have an outline. Thoughts?

![naamloos](https://cloud.githubusercontent.com/assets/1096535/14861815/148abe5e-0caf-11e6-9ae2-af6d54cd3073.png)

**Comment by xeolabs** [comment]
Might have to be a bounding box for now - a silhouette using this stencil technique is possible, but would take some work to make it efficient (requires making a copy of the selected object's mesh, along with special shader, stencil configs etc).  I will research it though for future use, because it looks like the best way to highlight things.

**Comment by aothms** [comment]
Indeed let's settle on a bounding box. The other complication is the 2px line drawing. Since `gl.lineWidth` does not support anything not equal to 1. in ANGLE, you have to implement your own line thickness and probably cannot (easily) re-use the positions for the triangles, meaning the implications on performance are probably not worth the trouble either.

**Comment by xeolabs** [comment]
I've added mouse-driven multiple selection to V2 if you'd like to give it a try. Let me know if there are any UX tweaks I should make.
