### ISSUE TITLE
Can`t import from BIM server to BIM surfer

### ISSUE THREAD

**Issue by dirkdejongh** [opensourceBIM/BIMsurfer-before2019#69]
HI all.

I setup an BIMserver at: http://bimserver.hostjava.net/bimserver-including_GUI-1.1.0-2012-06-24/login.jsp?origurl=/bimserver-including_GUI-1.1.0-2012-06-24/main.jsp

and a viewer at: http://dwanimations.org/bimserver/index.html
But when I try to import IFC via the BIMserver

**Comment by dirkdejongh** [comment]
http://dwanimations.org/loadIFC.jpg

here you can see what I get

**Comment by rehno-lindeque** [comment]
Sorry, Dirk I don't really have time to maintain the project at the moment... I'm not too sure what's wrong here. You might be able to get more information by opening the error console (CTRL + SHIFT + i) and seeing what messages appear there.

**Comment by cakewalker** [comment]
Hi Dirk,

This has been discussed a fair bit elsewhere on the BIMserver forum (http://support.bimserver.org). I believe it's likely to be due to browser security restrictions - you need to have both BIMserver and BIMsurfer running on the same domain and port. That should get around the error you're seeing.

Unfortunately you're likely to run into a different problem once you've overcome the current issue. BIMserver no longer seems to support the method of downloading data that BIMsurfer uses. Someone has written a revised app.js file to sort this - have a look at the bottom of the discussion

http://support.bimserver.org/bimserver/topics/bim_server_surfer_troubleshooting_500_error_when_trying_to_download_rest_data

for an explanation. Basically, you need to download https://dl.dropbox.com/u/580643/BIMsurfer/app.js and use it to replace app.js and app.min.js (strictly speaking you only have to replace one of these but it depends on the version of BIMsurfer you have - see below).

I don't know if you are aware, but the copy of BIMserver you have has BIMsurfer bundled with it. You can get to it, while you are browsing a project in BIMserver, by typing 'surf' (there's no box to type into - simply type it when no text fields have the focus). Unfortunately, this doesn't seem to work in Firefox, only Chrome (haven't tried other browsers). Hopefully, the BIMserver developers with implement a button to open BIMsurfer and also include the revised app.js.

Chris

**Comment by berlotti** [comment]
Try this with the new bimserver 1.2 beta. This connection between the two nog goes through json.

**Comment by berlotti** [comment]
fixed
